---
- name: Add nvidia-container-runtime repo
  command: "yum config-manager --add-repo=https://nvidia.github.io/nvidia-container-runtime/centos{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nvidia-container-runtime.repo"
  args:
    creates: '/etc/yum.repos.d/nvidia-container-runtime.repo'
  register: nvidia_container_runtime
  become: yes

- name: Install packages
  yum:
    update_cache: "{{ nvidia_container_runtime is changed }}"
    name:
      - nvidia-container-runtime-hook
  become: yes

- name: Set selinux type container_file_t on /dev/nvidia*
  shell: 'chcon -t container_file_t /dev/nvidia*'
  become: yes
